name: Test Project
on:
  push:
    branches:
      - main  # Change this to the appropriate branch name if needed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test  # Replace "coreect this" with the actual npm test command
